//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHyphenator.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHyphenator.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hyph_de_hyp {
            get {
                return ResourceManager.GetString("hyph_de_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ab1a
        ///.ab3l
        ///.abo2
        ///.ab3ol
        ///.ab1or
        ///.ab3s2
        ///.ab3u
        ///.ade3n
        ///.ae3
        ///.aft2
        ///.ag2a
        ///.ag4r
        ///.ag2u
        ///.ai2s
        ///.akt2a
        ///.al2e
        ///.al3k
        ///.al3lei
        ///.al5len
        ///.al3se
        ///.al4tei
        ///.alter6s5
        ///.alt1s
        ///.al2tu
        ///.ampe4
        ///.amt2s
        ///.ana1c
        ///.an3d2
        ///.anden6k
        ///.and4ri
        ///.an1er
        ///.ang2
        ///.an3gli
        ///.ang4s2
        ///.angst3
        ///.ani2s
        ///.an3k4
        ///.an3na
        ///.an3s2
        ///.an4si.
        ///.an3z2
        ///.aos4
        ///.ap5p6le.
        ///.aps2
        ///.ari1e
        ///.ar3k2a
        ///.ar4m3ac
        ///.ar4mun
        ///.ar2sc
        ///.ar4tan
        ///.ar4t3ei
        ///.arter4
        ///.ar6t5erh
        ///.ar2tr
        ///.arz2
        ///.as6sest
        ///.as2t
        ///.ata1
        ///.ate2
        ///.at4h
        ///.au3d
        ///.aue2
        ///.au4f3
        ///.aufs2
        ///.au2s1
        ///.au6stes
        ///.auß2
        ///.ax2
        ///.äm3
        ///.är6schl
        ///.ät2h
        ///.ät2s
        ///.äu3
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hyph_de_pat {
            get {
                return ResourceManager.GetString("hyph_de_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uni-ver-sity
        ///uni-ver-sit-ies
        ///how-ever
        ///ma-nu-script
        ///ma-nu-scripts
        ///re-ci-pro-city
        ///through-out
        ///some-thing
        ///.
        /// </summary>
        internal static string hyph_en_gb_hyp {
            get {
                return ResourceManager.GetString("hyph_en_gb_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ab4i
        ///.ab3ol
        ///.ace4
        ///.acet3
        ///.ach4
        ///.ac5tiva
        ///.ad4din
        ///.ad3e
        ///.ad3o
        ///.ae5d
        ///.aer3i
        ///.af3f
        ///.af3t
        ///.ag4a
        ///.ag5n
        ///.air3
        ///.al5im
        ///.al1k
        ///.al3le
        ///.am5ar
        ///.ama5te
        ///.am2i
        ///.am3pe
        ///.am3ph
        ///.an1
        ///.ana3b
        ///.ana3s
        ///.and2
        ///.an5da
        ///.an4el
        ///.an4en
        ///.an4gl
        ///.an4on.
        ///.an3s
        ///.ant3a
        ///.an3ti3
        ///.ant4ic
        ///.an4t5o
        ///.any5
        ///.aph5or
        ///.ap4i
        ///.ar5ab
        ///.ar5ap
        ///.ar4ci
        ///.ar5d
        ///.ar4e
        ///.ari4
        ///.ar4ise
        ///.ar4isi
        ///.ar5sen
        ///.art5icl
        ///.as1
        ///.as4q
        ///.as5sib
        ///.at5ar
        ///.ateli4
        ///.at5omise
        ///.at5omiz
        ///.at3r
        ///.at3t
        ///.au3b
        ///.au3g4u
        ///.aur4e5
        ///.aus5
        ///.authe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hyph_en_gb_pat {
            get {
                return ResourceManager.GetString("hyph_en_gb_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as-so-ciate
        ///as-so-ciates
        ///dec-li-na-tion
        ///oblig-a-tory
        ///phil-an-thropic
        ///present
        ///presents
        ///project
        ///projects
        ///reci-procity
        ///re-cog-ni-zance
        ///ref-or-ma-tion
        ///ret-ri-bu-tion
        ///ta-ble
        ///.
        /// </summary>
        internal static string hyph_en_us_hyp {
            get {
                return ResourceManager.GetString("hyph_en_us_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ach4
        ///.ad4der
        ///.af1t
        ///.al3t
        ///.am5at
        ///.an5c
        ///.ang4
        ///.ani5m
        ///.ant4
        ///.an3te
        ///.anti5s
        ///.ar5s
        ///.ar4tie
        ///.ar4ty
        ///.as3c
        ///.as1p
        ///.as1s
        ///.aster5
        ///.atom5
        ///.au1d
        ///.av4i
        ///.awn4
        ///.ba4g
        ///.ba5na
        ///.bas4e
        ///.ber4
        ///.be5ra
        ///.be3sm
        ///.be5sto
        ///.bri2
        ///.but4ti
        ///.cam4pe
        ///.can5c
        ///.capa5b
        ///.car5ol
        ///.ca4t
        ///.ce4la
        ///.ch4
        ///.chill5i
        ///.ci2
        ///.cit5r
        ///.co3e
        ///.co4r
        ///.cor5ner
        ///.de4moi
        ///.de3o
        ///.de3ra
        ///.de3ri
        ///.des4c
        ///.dictio5
        ///.do4t
        ///.du4c
        ///.dumb5
        ///.earth5
        ///.eas3i
        ///.eb4
        ///.eer4
        ///.eg2
        ///.el5d
        ///.el3em
        ///.enam3
        ///.en3g
        ///.en3s
        ///.eq5ui5t
        ///.er4ri
        ///.es3
        ///. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hyph_en_us_pat {
            get {
                return ResourceManager.GetString("hyph_en_us_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string hyph_es_hyp {
            get {
                return ResourceManager.GetString("hyph_es_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1b 4b. .b2 2bb 2bc 2bd 2bf 2bg 2b1h 2bj 2bk     2bm 2bn 2bp 2bq     2bs 2bt 2bv 2bw 2bx 2by 2bz
        ///1c 4c. .c2 2cb 2cc 2cd 2cf 2cg     2cj 2ck     2cm 2cn 2cp 2cq     2cs 2ct 2cv 2cw 2cx 2cy 2cz
        ///1d 4d. .d2 2db 2dc 2dd 2df 2dg 2d1h 2dj 2dk 2dl 2dm 2dn 2dp 2dq     2ds 2dt 2dv 2dw 2dx 2dy 2dz
        ///1f 4f. .f2 2fb 2fc 2fd 2ff 2fg 2f1h 2fj 2fk     2fm 2fn 2fp 2fq     2fs 2ft 2fv 2fw 2fx 2fy 2fz
        ///1g 4g. .g2 2gb 2gc 2gd 2gf 2gg 2g1h 2gj 2gk     2gm 2gn 2gp 2gq     2gs 2gt 2gv 2gw 2gx 2gy 2gz
        ///   4h. 2hb 2hc 2hd 2hf 2hg 2h1h 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hyph_es_pat {
            get {
                return ResourceManager.GetString("hyph_es_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ас-бест
        ///бездн
        ///биз-нес-мен
        ///буй-нак-ске
        ///вбли-зи
        ///взба-ла-муть-ся
        ///вздрем-нешь
        ///во-до-сли-вом
        ///волж-ске
        ///воп-лем
        ///вопль
        ///вост-ра
        ///во-ткать
        ///во-ткем
        ///во-ткешь
        ///во-тку
        ///во-ткут
        ///впол-обо-ро-та
        ///впол-уха
        ///все-во-лож-ске
        ///вцспс
        ///га-рем-но-го
        ///го-ло-дра-нец
        ///грэс
        ///дву-зу-бец
        ///днепр
        ///добре-ем
        ///до-бре-ем-ся
        ///добре-ет
        ///добре-е-те
        ///до-бре-е-тесь
        ///до-бре-ет-ся
        ///добре-ешь
        ///до-бре-ешь-ся
        ///добрею
        ///до-бре-юсь
        ///добре-ют
        ///до-бре-ют-ся
        ///до-бре-сти
        ///до-бро-дят
        ///до-брось
        ///до-брось-те
        ///до-бро-сят
        ///до-бро-шу
        ///домну
        ///доп-пель
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hyph_ru_hyp {
            get {
                return ResourceManager.GetString("hyph_ru_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .аб1р
        ///.аг1ро
        ///.ади2
        ///.аи2
        ///.ак1р
        ///.аль3я
        ///.ар2т1о2
        ///.ас1то
        ///.аст1р
        ///.ау2
        ///.би2о
        ///.во2б3л
        ///.во3ж2д
        ///.го2ф
        ///.дек2
        ///.де1кв
        ///.ди2ак
        ///.ди1о
        ///.до3п
        ///.до3т2
        ///.епи3
        ///.зав2р
        ///.за3м2н
        ///.за3п
        ///.иг1р
        ///.изг2
        ///.из3н
        ///.ии2
        ///.ик1р
        ///.ио2
        ///.ио4на
        ///.ис3
        ///.ле2о
        ///.ле2п3р
        ///.лес1к
        ///.ль2
        ///.люст1
        ///.ме2ж1у2
        ///.ми1ом
        ///.мо2к1
        ///.му2шт1
        ///.на1в
        ///.на3т
        ///.на3ш2
        ///.не3вн
        ///.не1др
        ///.не1з2
        ///.не1сл
        ///.не1с2ц
        ///.не3т
        ///.нос1к
        ///.нук1л
        ///.обо3ж2
        ///.ово1
        ///.ог3н
        ///.оз4
        ///.ос2ка
        ///.ос2п
        ///.ос3пи
        ///.от1в
        ///.от1ро
        ///.от1ру
        ///.от1уж
        ///.по3в2
        ///.по3ж2
        ///.поз2н
        ///.прос2
        ///. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hyph_ru_pat {
            get {
                return ResourceManager.GetString("hyph_ru_pat", resourceCulture);
            }
        }
    }
}
